import AppFrame from "@/components/AppFrame";
import QueryError from "@/components/QueryError";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BookOpen, Loader2, MapPin, Plus, Users } from "lucide-react";
import { useState } from "react";

export default function CirclesPage() {
  const { user } = useAuth();
  const circles = trpc.circles.list.useQuery(undefined, { enabled: Boolean(user?.organizationId) });
  const members = trpc.organization.members.useQuery(undefined, { enabled: user?.role === "admin" || user?.role === "teacher" });
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: "", mosqueName: "", teacherId: "", level: "beginner" as "beginner" | "intermediate" | "advanced", capacity: "20", meetingSummary: "" });
  const utils = trpc.useUtils();
  const create = trpc.circles.create.useMutation({ onSuccess: () => { utils.circles.list.invalidate(); setOpen(false); setForm({ name: "", mosqueName: "", teacherId: "", level: "beginner", capacity: "20", meetingSummary: "" }); } });
  const teachers = members.data?.filter(member => member.role === "teacher") ?? [];
  if (circles.error) return <AppFrame eyebrow="إدارة الحلقات" title="تعذر تحميل الحلقات" description="تحقق من الاتصال ثم أعد المحاولة."><QueryError message={circles.error.message} onRetry={() => circles.refetch()} /></AppFrame>;
  if (members.error && (user?.role === "admin" || user?.role === "teacher")) return <AppFrame eyebrow="إدارة الحلقات" title="تعذر تحميل أعضاء المؤسسة" description="تحقق من الاتصال ثم أعد المحاولة."><QueryError message={members.error.message} onRetry={() => members.refetch()} /></AppFrame>;
  return <AppFrame eyebrow="إدارة الحلقات" title="الحلقات والمجموعات" description="أنشئ حلقات المؤسسة، وحدد المعلم المسؤول والبرنامج الزمني، ثم تابع الطلاب المسجلين فيها." action={user?.role === "admin" ? <Button onClick={() => setOpen(!open)} className="h-10 rounded-xl bg-[#276654] text-white hover:bg-[#1e5545]"><Plus className="size-4" />إضافة حلقة</Button> : undefined}>
    {open ? <form onSubmit={event => { event.preventDefault(); create.mutate({ name: form.name, mosqueName: form.mosqueName, teacherId: Number(form.teacherId), level: form.level, capacity: Number(form.capacity), meetingSummary: form.meetingSummary }); }} className="rounded-3xl border border-[#d6e5dc] bg-[#f8fcf9] p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-xl font-semibold text-[#193a31]">بيانات الحلقة الجديدة</h2><span className="text-xs text-[#77837c]">يظهر المعلمون بعد تسجيل دخولهم وربطهم بالمؤسسة</span></div><div className="grid gap-4 md:grid-cols-2"><label className="form-label">اسم الحلقة<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="form-input" placeholder="حلقة الفجر" /></label><label className="form-label">المسجد أو المكان<input required value={form.mosqueName} onChange={event => setForm({ ...form, mosqueName: event.target.value })} className="form-input" placeholder="مسجد النور" /></label><label className="form-label">المعلم المسؤول<select required value={form.teacherId} onChange={event => setForm({ ...form, teacherId: event.target.value })} className="form-input"><option value="">اختر معلماً</option>{teachers.map(teacher => <option key={teacher.id} value={teacher.id}>{teacher.name ?? teacher.email ?? `مستخدم #${teacher.id}`}</option>)}</select></label><label className="form-label">المستوى<select value={form.level} onChange={event => setForm({ ...form, level: event.target.value as typeof form.level })} className="form-input"><option value="beginner">مبتدئ</option><option value="intermediate">متوسط</option><option value="advanced">متقدم</option></select></label><label className="form-label">السعة<input type="number" min="1" max="200" value={form.capacity} onChange={event => setForm({ ...form, capacity: event.target.value })} className="form-input" /></label><label className="form-label">موعد اللقاء<input required value={form.meetingSummary} onChange={event => setForm({ ...form, meetingSummary: event.target.value })} className="form-input" placeholder="الأحد والثلاثاء بعد المغرب" /></label></div>{!teachers.length ? <p className="mt-4 rounded-xl bg-[#fff4de] p-3 text-sm text-[#805d28]">لا يوجد معلم مضاف بعد. اجعل المستخدم يسجل الدخول ثم عيّن دوره «معلم» من إدارة المستخدمين.</p> : null}{create.error ? <p className="mt-4 text-sm text-red-700">{create.error.message}</p> : null}<div className="mt-5 flex gap-3"><Button disabled={create.isPending || !teachers.length} className="rounded-xl bg-[#276654] text-white hover:bg-[#1e5545]">{create.isPending ? <Loader2 className="size-4 animate-spin" /> : "حفظ الحلقة"}</Button><Button type="button" variant="outline" onClick={() => setOpen(false)} className="rounded-xl">إلغاء</Button></div></form> : null}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{circles.isLoading ? <div className="col-span-full grid place-items-center py-16"><Loader2 className="size-6 animate-spin text-[#276654]" /></div> : circles.data?.length ? circles.data.map(circle => <article key={circle.id} className="rounded-3xl border border-[#dfe8e1] bg-white p-6 shadow-[0_15px_35px_-30px_rgba(21,58,48,0.45)]"><div className="flex items-start justify-between"><span className="flex size-11 items-center justify-center rounded-2xl bg-[#ecf4ed] text-[#2b6d59]"><BookOpen className="size-5" /></span><span className="rounded-full bg-[#f7efe1] px-3 py-1 text-xs font-semibold text-[#8d6a2d]">{circle.level === "beginner" ? "مبتدئ" : circle.level === "intermediate" ? "متوسط" : "متقدم"}</span></div><h2 className="mt-5 font-display text-xl font-semibold text-[#193a31]">{circle.name}</h2><p className="mt-2 flex items-center gap-2 text-sm text-[#718078]"><MapPin className="size-4" />{circle.mosqueName}</p><div className="mt-5 flex items-center justify-between border-t border-[#edf1ed] pt-4 text-sm"><span className="flex items-center gap-2 text-[#66746c]"><Users className="size-4" />السعة {circle.capacity} طالباً</span><span className="font-semibold text-[#2e6c58]">{circle.meetingSummary}</span></div></article>) : <div className="col-span-full rounded-3xl border border-dashed border-[#c9d9ce] bg-[#fbfdfb] py-16 text-center"><BookOpen className="mx-auto size-9 text-[#8aaa9b]" /><h2 className="mt-4 font-display text-xl font-semibold text-[#264439]">لا توجد حلقات بعد</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-7 text-[#77837c]">ابدأ بإضافة المعلمين ثم أنشئ أول حلقة، أو استعرض الوضع التجريبي من الصفحة العامة.</p></div>}</div>
  </AppFrame>;
}
