import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { BookOpenCheck, GraduationCap, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";

export default function Login() {
  const roles = [{ key: "admin", label: "المدير", copy: "إدارة الحلقات والمؤشرات", icon: ShieldCheck }, { key: "teacher", label: "المعلم", copy: "الحضور والمتابعة اليومية", icon: BookOpenCheck }, { key: "guardian", label: "ولي الأمر", copy: "تقدم الأبناء وتقاريرهم", icon: UsersRound }, { key: "student", label: "الطالب", copy: "مساري ومهامي ونقاطي", icon: GraduationCap }];
  return <main className="min-h-screen overflow-hidden bg-[#f8f7ef] px-5 py-8 text-[#174238] sm:grid sm:place-items-center"><section className="grid w-full max-w-5xl overflow-hidden rounded-[2rem] border border-[#e4dfcf] bg-white shadow-[0_24px_80px_rgba(32,72,62,.12)] md:grid-cols-[.9fr_1.1fr]"><div className="relative overflow-hidden bg-[#174238] p-8 text-white sm:p-12"><div className="islamic-grid absolute inset-0 opacity-30" /><div className="relative"><p className="font-kufi text-lg font-bold text-[#ffe3a4]">أثر</p><h1 className="mt-12 font-kufi text-2xl font-bold leading-[1.7] sm:text-3xl">دخول منظم لكل رحلة قرآنية.</h1><p className="mt-5 max-w-sm text-sm leading-8 text-white/70">تُعرض الأدوات والبيانات بحسب دورك: إدارة المركز، المعلم، ولي الأمر، أو الطالب.</p><div className="mt-10 space-y-4">{[{ icon: ShieldCheck, text: "صلاحيات محمية لكل حساب" }, { icon: UsersRound, text: "حلقات وأسر مرتبطة بوضوح" }, { icon: BookOpenCheck, text: "سجل متابعة وإشعارات داخلية" }].map(item => <div key={item.text} className="flex items-center gap-3 text-sm text-white/85"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/10 text-[#ffe3a4]"><item.icon className="h-4 w-4" /></span>{item.text}</div>)}</div></div></div><div className="flex flex-col justify-center p-8 sm:p-12"><p className="font-kufi text-sm font-bold text-[#b8892d]">مرحباً بك</p><h2 className="mt-3 font-kufi text-2xl font-bold">دخول المنصة</h2><p className="mt-3 text-sm leading-7 text-[#728079]">استخدم حسابك المصرح به للوصول إلى لوحة الدور المرتبط بك. يتم تحديد الدور من قبل إدارة المنصة.</p><Button onClick={() => startLogin()} className="mt-6 h-12 rounded-xl bg-[#174238] text-sm font-bold hover:bg-[#21594f]">المتابعة إلى الدخول</Button><div className="mt-7 border-t border-[#ece8da] pt-5"><p className="text-xs font-bold text-[#6f7d74]">استعرض تجربة كل دور</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{roles.map(role => <Link key={role.key} href={`/dashboard?preview=${role.key}`} className="group flex items-center gap-2 rounded-xl border border-[#e4e1d5] p-2.5 transition hover:border-[#6fa08f] hover:bg-[#f5f8f2]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf4ee] text-[#397c6b]"><role.icon className="h-3.5 w-3.5" /></span><span className="min-w-0"><span className="block text-[11px] font-bold">{role.label}</span><span className="mt-0.5 block truncate text-[9px] text-[#7b867e]">{role.copy}</span></span></Link>)}</div></div><Link href="/" className="mt-5 text-center text-xs font-bold text-[#397c6b]">العودة إلى الصفحة الرئيسية</Link></div></section></main>;
}
