import { trpc } from "@/lib/trpc";
import { Bell, BookMarked, CalendarDays, CircleDollarSign, GraduationCap, Trophy } from "lucide-react";

function number(value: number) { return new Intl.NumberFormat("ar-SA").format(value); }
function formattedDate(date: Date | string | null | undefined) { return date ? new Intl.DateTimeFormat("ar-SA", { weekday: "short", day: "numeric", month: "short" }).format(new Date(date)) : "قريباً"; }

export default function LiveDashboardSummary({ isAuthenticated }: { isAuthenticated: boolean }) {
  const dashboardQuery = trpc.platform.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  if (!isAuthenticated) return null;
  const dashboard = dashboardQuery.data;
  if (dashboardQuery.isLoading) return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-28 animate-pulse rounded-[1.4rem] bg-[#edf0e8]" />)}</div>;
  const metrics = dashboard?.metrics || { circles: 0, students: 0, points: 0, unreadNotifications: 0 };
  const cards = [{ label: "الحلقات", value: metrics.circles, icon: BookMarked, tone: "bg-[#eaf3ea] text-[#397c6b]" }, { label: "الطلاب المرتبطون", value: metrics.students, icon: GraduationCap, tone: "bg-[#fff3dc] text-[#ae8025]" }, { label: "رصيد النقاط", value: metrics.points, icon: Trophy, tone: "bg-[#edf3f6] text-[#4d8495]" }, { label: "تنبيهات جديدة", value: metrics.unreadNotifications, icon: Bell, tone: "bg-[#fbecec] text-[#bd6962]" }];
  return <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => <article key={card.label} className="soft-card rounded-[1.4rem] border border-[#e5e1d4] bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-[#78847c]">{card.label}</p><p className="mt-3 font-kufi text-xl font-bold text-[#174238]">{number(card.value)}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${card.tone}`}><card.icon className="h-4.5 w-4.5" /></span></div></article>)}</section><div className="grid gap-6 xl:grid-cols-2"><section className="soft-card rounded-[1.6rem] border border-[#e6e1d2] bg-white p-5 sm:p-6"><h2 className="font-kufi text-sm font-bold">الجلسات القادمة</h2><p className="mt-1.5 text-xs text-[#7c877f]">مواعيد متاحة لحسابك حالياً.</p><div className="mt-5 space-y-3">{dashboard?.upcomingSessions.map(session => <div key={session.id} className="flex items-center gap-3 rounded-xl bg-[#f7f8f2] p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white text-[#397c6b]"><CalendarDays className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{session.title}</p><p className="mt-1 text-[10px] text-[#7a867e]">{session.circleName} · {formattedDate(session.startsAt)}</p></div></div>)}{dashboard?.upcomingSessions.length === 0 && <p className="rounded-xl border border-dashed border-[#ddd8c9] p-5 text-center text-xs text-[#8a958c]">لا توجد جلسات قادمة.</p>}</div></section><section className="soft-card rounded-[1.6rem] border border-[#e6e1d2] bg-white p-5 sm:p-6"><h2 className="font-kufi text-sm font-bold">استحقاقات قريبة</h2><p className="mt-1.5 text-xs text-[#7c877f]">مهام مرتبطة بالطلاب المسموح بمتابعتهم.</p><div className="mt-5 space-y-3">{dashboard?.pendingTasks.map(task => <div key={task.id} className="flex items-center gap-3 rounded-xl bg-[#fffaf0] p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white text-[#b8882b]"><CircleDollarSign className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{task.title}</p><p className="mt-1 text-[10px] text-[#7a867e]">ينتهي {formattedDate(task.dueAt)}</p></div><span className="text-xs font-bold text-[#b8882b]">+{number(task.pointsAvailable)}</span></div>)}{dashboard?.pendingTasks.length === 0 && <p className="rounded-xl border border-dashed border-[#ddd8c9] p-5 text-center text-xs text-[#8a958c]">لا توجد مهام قادمة.</p>}</div></section></div></div>;
}
