import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Mail, MessageCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function LiveMessagesPanel({ isAuthenticated }: { isAuthenticated: boolean }) {
  const utils = trpc.useUtils();
  const [recipientId, setRecipientId] = useState("");
  const [body, setBody] = useState("");
  const recipientsQuery = trpc.platform.messages.recipients.useQuery(undefined, { enabled: isAuthenticated });
  const messagesQuery = trpc.platform.messages.list.useQuery(undefined, { enabled: isAuthenticated });
  const sendMessage = trpc.platform.messages.send.useMutation({ onSuccess: () => { utils.platform.messages.list.invalidate(); utils.platform.notifications.list.invalidate(); setBody(""); toast.success("تم إرسال الرسالة وإشعار المستلم."); }, onError: error => toast.error(error.message) });
  const markIncomingRead = trpc.platform.messages.markIncomingRead.useMutation({ onSuccess: () => { utils.platform.messages.list.invalidate(); toast.success("تم تعليم الرسائل الواردة كمقروءة."); }, onError: error => toast.error(error.message) });
  if (!isAuthenticated) return null;
  return <section className="soft-card rounded-[1.6rem] border border-[#e6e1d2] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-kufi text-sm font-bold">مراسلة مرتبطة بالحلقات</h2><p className="mt-1.5 text-xs text-[#7c877f]">تظهر فقط الحسابات المرتبطة بك عبر الحلقة أو العلاقة العائلية.</p></div><MessageCircle className="h-5 w-5 text-[#397c6b]" /></div><form onSubmit={event => { event.preventDefault(); if (!recipientId) { toast.error("اختر المستلم أولاً."); return; } sendMessage.mutate({ recipientId: Number(recipientId), body }); }} className="mt-5 grid gap-3 md:grid-cols-[220px_1fr_auto]"><select value={recipientId} onChange={event => setRecipientId(event.target.value)} className="h-11 rounded-xl border border-[#e2e0d4] bg-[#fcfdf9] px-3 text-xs outline-none"><option value="">اختر المستلم</option>{recipientsQuery.data?.map(recipient => <option key={recipient.id} value={recipient.id}>{recipient.name || `حساب #${recipient.id}`}</option>)}</select><input required value={body} onChange={event => setBody(event.target.value)} className="h-11 rounded-xl border border-[#e2e0d4] bg-[#fcfdf9] px-3 text-xs outline-none" placeholder="اكتب رسالتك باختصار ووضوح" /><Button disabled={sendMessage.isPending} type="submit" className="h-11 rounded-xl bg-[#174238] px-4"><Mail className="h-4 w-4" /></Button></form>{recipientsQuery.data?.length === 0 && <p className="mt-3 text-[11px] text-[#a06f26]">لا توجد علاقات مراسلة مصرح بها بعد.</p>}<div className="mt-5 flex items-center justify-between"><p className="text-xs font-bold text-[#596e65]">آخر الرسائل</p><button onClick={() => markIncomingRead.mutate()} disabled={markIncomingRead.isPending} className="text-[11px] font-bold text-[#397c6b] disabled:opacity-50">تعليم الوارد كمقروء</button></div><div className="mt-2 space-y-2">{messagesQuery.data?.slice(0, 4).map(message => <div key={message.id} className="flex items-center gap-2 rounded-xl bg-[#f7f8f2] p-3 text-xs leading-6 text-[#566c62]"><span className="min-w-0 flex-1">{message.body}</span>{message.recipientId !== Number(recipientId || 0) && !message.isRead && <span className="h-2 w-2 rounded-full bg-[#d2a94f]" />}</div>)}{messagesQuery.data?.length === 0 && <div className="rounded-xl border border-dashed border-[#ddd8c9] px-4 py-5 text-center text-xs text-[#8a958c]">لا توجد رسائل بعد.</div>}</div></section>;
}
