import { Loader2, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type TrendPoint = { key: string; weekStart: Date | string; present: number; attendanceTotal: number; progressCount: number; points: number };

export default function StudentTrendChart({ data, loading }: { data: TrendPoint[]; loading: boolean }) {
  const formatted = data.map(point => ({ ...point, label: new Date(point.weekStart).toLocaleDateString("ar-SA", { month: "short", day: "numeric" }) }));
  return <section className="rounded-3xl border border-[#dfe8e1] bg-white p-6 shadow-[0_16px_40px_-34px_rgba(21,58,48,0.5)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e8f2eb] text-[#2f6d58]"><TrendingUp className="size-5" /></span><div><h2 className="font-display text-xl font-semibold text-[#193a31]">اتجاه التقدم الأسبوعي</h2><p className="text-sm text-[#718078]">الحضور وسجلات المتابعة والنقاط، بناءً على بيانات الطالب الفعلية.</p></div></div><span className="rounded-full bg-[#f7efdf] px-3 py-1 text-xs font-bold text-[#8b6a31]">تفاعلي</span></div>{loading ? <div className="grid h-72 place-items-center"><Loader2 className="size-7 animate-spin text-[#276654]" /></div> : <div className="mt-6 grid gap-7 xl:grid-cols-2"><div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><AreaChart data={formatted} margin={{ top: 8, left: -18, right: 4, bottom: 0 }}><defs><linearGradient id="atharAttendance" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#2f7a63" stopOpacity={0.32} /><stop offset="95%" stopColor="#2f7a63" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#dce8df" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#728078", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: "#728078", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ direction: "rtl", borderRadius: 12, border: "1px solid #dfe8e1" }} labelStyle={{ color: "#29483e" }} /><Legend /><Area isAnimationActive={false} type="monotone" dataKey="present" name="حاضر" stroke="#2f7a63" strokeWidth={2.5} fill="url(#atharAttendance)" /><Area isAnimationActive={false} type="monotone" dataKey="attendanceTotal" name="جلسات مسجلة" stroke="#b88532" strokeWidth={2} fill="transparent" /></AreaChart></ResponsiveContainer></div><div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><BarChart data={formatted} margin={{ top: 8, left: -18, right: 4, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#dce8df" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#728078", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: "#728078", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ direction: "rtl", borderRadius: 12, border: "1px solid #dfe8e1" }} labelStyle={{ color: "#29483e" }} /><Legend /><Bar isAnimationActive={false} dataKey="progressCount" name="متابعات" fill="#347960" radius={[6, 6, 0, 0]} /><Bar isAnimationActive={false} dataKey="points" name="نقاط" fill="#c39239" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></div>}</section>;
}
